In [1]:
import pandas as pd

In [2]:
cd C:\Users\Mukaffi\Regional speech

C:\Users\Mukaffi\Regional speech


In [3]:
test_data = pd.read_csv("test.csv")

In [4]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")
validation_data = pd.read_csv("dev.csv")

In [5]:
train_data.head(5)

en  \
0  « Lucy va-t-elle toujours bien ? demanda-t-il,...   
1  Whilst we were thus enjoying the sweets of rep...   
2  "It was very essential for Stapleton to get so...   
3  Provided that she was left alone to stroll in ...   
4  "Yes," replied the gypsy; "it is to be brother...   

                                                  fr  
0  "Does Lucy bear up well?" he asked, when he ha...  
1  Pendant que chacun s'abandonnait ainsi à toute...  
2  « L’essentiel était pour Stapleton de se procu...  
3  Pourvu qu’on la laissât seule errer dans son b...  
4  – Oui, répondit l’égyptienne. C’est être frère...

In [6]:
# Rename the columns to match the expected format
train_data.rename(columns={'en': 'input_text', 'fr': 'labels'}, inplace=True)
train_data.head()

input_text  \
0  « Lucy va-t-elle toujours bien ? demanda-t-il,...   
1  Whilst we were thus enjoying the sweets of rep...   
2  "It was very essential for Stapleton to get so...   
3  Provided that she was left alone to stroll in ...   
4  "Yes," replied the gypsy; "it is to be brother...   

                                              labels  
0  "Does Lucy bear up well?" he asked, when he ha...  
1  Pendant que chacun s'abandonnait ainsi à toute...  
2  « L’essentiel était pour Stapleton de se procu...  
3  Pourvu qu’on la laissât seule errer dans son b...  
4  – Oui, répondit l’égyptienne. C’est être frère...

In [7]:
test_data.head(5)

en  \
0  Altamira looked at her in astonishment; Julien...   
1  "Already empty, ~cor−boeuf~! and I have no mor...   
2  The deaf man had closed it behind him when he ...   
3     So you'll do no more than say Farewell, Jane?"   
4  You don't deceive a woman like me, my dear fri...   

                                                  fr  
0  Altamira la regarda étonné, Julien ne daigna p...  
1  « Déjà vide, corbœuf ! et je n’ai plus d’argent !  
2  Le sourd en entrant dans la galerie l’avait fe...  
3  Mais non, cela ne me suffirait pas; ainsi donc...  
4  On ne trompe pas une femme comme moi, mon cher...

In [8]:
# Rename the columns to match the expected format
test_data.rename(columns={'en': 'input_text', 'fr': 'labels'}, inplace=True)
test_data.head()

input_text  \
0  Altamira looked at her in astonishment; Julien...   
1  "Already empty, ~cor−boeuf~! and I have no mor...   
2  The deaf man had closed it behind him when he ...   
3     So you'll do no more than say Farewell, Jane?"   
4  You don't deceive a woman like me, my dear fri...   

                                              labels  
0  Altamira la regarda étonné, Julien ne daigna p...  
1  « Déjà vide, corbœuf ! et je n’ai plus d’argent !  
2  Le sourd en entrant dans la galerie l’avait fe...  
3  Mais non, cela ne me suffirait pas; ainsi donc...  
4  On ne trompe pas une femme comme moi, mon cher...

In [9]:
validation_data.head(5)

en  \
0  After my mother's death, I wash my hands of yo...   
1  We took him by a shoulder each and turned him ...   
2           Now you talk, my dear." "You pardon me?"   
3  He was meditating an enlarged programme; that ...   
4  He asked him how many shirts he had ordered fr...   

                                                  fr  
0  après la mort de ma mère, je ne m'inquiète plu...  
1  Nous le prîmes chacun par une épaule et l’éten...  
2     -- Nous verrons», dit majestueusement Porthos.  
3  Il méditait d'élargir son programme, l'affinem...  
4  Il lui demanda combien il avait pris de chemis...

In [10]:
# Rename the columns to match the expected format
validation_data.rename(columns={'en': 'input_text', 'fr': 'labels'}, inplace=True)
validation_data.head()

input_text  \
0  After my mother's death, I wash my hands of yo...   
1  We took him by a shoulder each and turned him ...   
2           Now you talk, my dear." "You pardon me?"   
3  He was meditating an enlarged programme; that ...   
4  He asked him how many shirts he had ordered fr...   

                                              labels  
0  après la mort de ma mère, je ne m'inquiète plu...  
1  Nous le prîmes chacun par une épaule et l’éten...  
2     -- Nous verrons», dit majestueusement Porthos.  
3  Il méditait d'élargir son programme, l'affinem...  
4  Il lui demanda combien il avait pris de chemis...

In [11]:
!pip install transformers torch pandas

In [12]:
import transformers
import torch

print("transformers version:", transformers.__version__)
print("torch version:", torch.__version__)


transformers version: 4.35.2
torch version: 2.1.1+cu118


In [13]:
#pip install transformers==4.35.2

In [14]:
#pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 

In [15]:
import torch

# Check if GPU (CUDA) is available
if torch.cuda.is_available():
    # Get the number of available GPUs
    num_gpus = torch.cuda.device_count()
    
    # Display GPU information
    for i in range(num_gpus):
        gpu_name = torch.cuda.get_device_name(i)
        print(f"GPU {i}: {gpu_name}")
else:
    print("No GPU (CUDA) devices available.")


GPU 0: NVIDIA GeForce RTX 3050


In [16]:
!pip install sacrebleu

In [17]:
!pip install rouge_score

In [18]:
!pip install sentencepiece

In [19]:
!pip install transformers[sentencepiece]

In [20]:
!transformers-cli cache clear

usage: transformers-cli <command> [<args>]
Transformers CLI tool: error: argument {convert,download,env,run,serve,login,whoami,logout,repo,add-new-model,add-new-model-like,lfs-enable-largefiles,lfs-multipart-upload,pt-to-tf}: invalid choice: 'cache' (choose from 'convert', 'download', 'env', 'run', 'serve', 'login', 'whoami', 'logout', 'repo', 'add-new-model', 'add-new-model-like', 'lfs-enable-largefiles', 'lfs-multipart-upload', 'pt-to-tf')


In [21]:
!pip install transformers[torch]

In [22]:
!pip install accelerate -U

   ---------------------------------------- 0.0/265.7 kB ? eta -:--:--
   ---- ----------------------------------- 30.7/265.7 kB 1.4 MB/s eta 0:00:01
   ---- ----------------------------------- 30.7/265.7 kB 1.4 MB/s eta 0:00:01
   --------- ----------------------------- 61.4/265.7 kB 544.7 kB/s eta 0:00:01
   ---------------- --------------------- 112.6/265.7 kB 731.4 kB/s eta 0:00:01
   -------------------- ----------------- 143.4/265.7 kB 711.9 kB/s eta 0:00:01
   --------------------------------- ---- 235.5/265.7 kB 962.7 kB/s eta 0:00:01
   ------------------------------------ - 256.0/265.7 kB 874.6 kB/s eta 0:00:01
   -------------------------------------- 265.7/265.7 kB 860.1 kB/s eta 0:00:00
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.24.1
    Uninstalling accelerate-0.24.1:
      Successfully uninstalled accelerate-0.24.1


In [23]:
!pip install git+https://github.com/csebuetnlp/normalizer

  Cloning https://github.com/csebuetnlp/normalizer to c:\users\mukaffi\appdata\local\temp\pip-req-build-0ezx7zty
  Resolved https://github.com/csebuetnlp/normalizer to commit d405944dde5ceeacb7c2fd3245ae2a9dea5f35c9
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'


  Running command git clone --filter=blob:none --quiet https://github.com/csebuetnlp/normalizer 'C:\Users\Mukaffi\AppData\Local\Temp\pip-req-build-0ezx7zty'


In [24]:
!pip install --upgrade pip

In [25]:
!pip install transformers==4.10.3

  Using cached transformers-4.10.3-py3-none-any.whl (2.8 MB)
     ---------------------------------------- 0.0/212.7 kB ? eta -:--:--
     ----- ------------------------------- 30.7/212.7 kB 660.6 kB/s eta 0:00:01
     ----- ------------------------------- 30.7/212.7 kB 660.6 kB/s eta 0:00:01
     ------------ ------------------------ 71.7/212.7 kB 435.7 kB/s eta 0:00:01
     ------------------- ---------------- 112.6/212.7 kB 656.4 kB/s eta 0:00:01
     ------------------------- ---------- 153.6/212.7 kB 610.0 kB/s eta 0:00:01
     ------------------------------------ 212.7/212.7 kB 761.2 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Failed to build tokenizers


  error: subprocess-exited-with-error
  
  exit code: 1
  
  [51 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\tokenizers
  copying py_src\tokenizers\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers
  creating build\lib.win-amd64-cpython-311\tokenizers\models
  copying py_src\tokenizers\models\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\models
  creating build\lib.win-amd64-cpython-311\tokenizers\decoders
  copying py_src\tokenizers\decoders\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\decoders
  creating build\lib.win-amd64-cpython-311\tokenizers\normalizers
  copying py_src\tokenizers\normalizers\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\normalizers
  creating build\lib.win-amd64-cpython-311\tokenizers\pre_tokenizers
  copying py_src\tokenizers\pre_tokenizers\__init__.py -> build\lib.win-amd64-cpython-31

In [26]:
!pip install torch transformers

In [27]:
#!pip install accelerate==0.20.3

In [28]:
!pip install git+https://github.com/csebuetnlp/normalizer

  Cloning https://github.com/csebuetnlp/normalizer to c:\users\mukaffi\appdata\local\temp\pip-req-build-fakv8ob_
  Resolved https://github.com/csebuetnlp/normalizer to commit d405944dde5ceeacb7c2fd3245ae2a9dea5f35c9
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'


  Running command git clone --filter=blob:none --quiet https://github.com/csebuetnlp/normalizer 'C:\Users\Mukaffi\AppData\Local\Temp\pip-req-build-fakv8ob_'


In [29]:
pip install protobuf==3.20

Note: you may need to restart the kernel to use updated packages.


In [30]:
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")


# **Load the model and tokenizer**

In [31]:
'''import torch
from transformers import MT5ForConditionalGeneration, AutoTokenizer
#https://huggingface.co/docs/transformers/model_doc/mt5
model_name = "google/mt5-small" # The variations it has -> mt5-small: 6, mt5-base: 12,mt5-large: 24, mt5-xl: 24, mt5-xxl: 24
model = MT5ForConditionalGeneration.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")'''



'import torch\nfrom transformers import MT5ForConditionalGeneration, AutoTokenizer\n#https://huggingface.co/docs/transformers/model_doc/mt5\nmodel_name = "google/mt5-small" # The variations it has -> mt5-small: 6, mt5-base: 12,mt5-large: 24, mt5-xl: 24, mt5-xxl: 24\nmodel = MT5ForConditionalGeneration.from_pretrained(model_name)\ntokenizer = AutoTokenizer.from_pretrained(model_name)\ndevice = torch.device("cuda" if torch.cuda.is_available() else "cpu")'

In [32]:
import torch
from normalizer import normalize
from transformers import MT5ForConditionalGeneration, AutoTokenizer ,DataCollatorForSeq2Seq, Trainer, TrainingArguments
import os


model_name = "google/mt5-small" 
model = MT5ForConditionalGeneration.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


In [33]:
from torch.utils.data import Dataset, DataLoader
class Seq2SeqDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=128):
        self.input_text = data['input_text'].apply(normalize).tolist()
        self.labels = data['labels'].apply(normalize).tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.input_text)

    def __getitem__(self, idx):
        input_text = self.input_text[idx]
        label_text = self.labels[idx]

        # Tokenize the input text
        input_encodings = self.tokenizer(
            input_text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        # Tokenize the label text to get its 'input_ids' and 'attention_mask'
        label_encodings = self.tokenizer(
            label_text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        return {
            'input_ids': input_encodings['input_ids'].squeeze(),
            'attention_mask': input_encodings['attention_mask'].squeeze(),
            'labels': label_encodings['input_ids'].squeeze(),
        }

In [34]:
# Modify the data collation process to handle PyTorch tensors correctly
class MyDataCollatorForSeq2Seq(DataCollatorForSeq2Seq):
    def __call__(self, features):
        batch = {}
        batch["input_ids"] = torch.stack([feature["input_ids"] for feature in features])
        batch["attention_mask"] = torch.stack([feature["attention_mask"] for feature in features])

        # Labels should be processed differently for PyTorch tensors
        if isinstance(features[0]["labels"], torch.Tensor):
            batch["labels"] = torch.stack([feature["labels"] for feature in features])
        else:
            # Convert the list of lists to a PyTorch tensor
            batch["labels"] = torch.tensor([feature["labels"] for feature in features])

        return batch

In [35]:
# Create train , test and validation datasets
train_dataset = Seq2SeqDataset(train_data, tokenizer)
test_dataset = Seq2SeqDataset(test_data, tokenizer)
validation_dataset = Seq2SeqDataset(validation_data, tokenizer)

# Create train , test and validation dataloaders
train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True)  #batch_size=32
test_dataloader = DataLoader(test_dataset, batch_size=32) #batch_size=32
validation_dataloader = DataLoader(validation_dataset, batch_size=32) #batch_size=32


In [36]:
# Move the model to the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [44]:
# Move the model to the device (CPU or GPU)
model.to(device)

MT5ForConditionalGeneration(
  (shared): Embedding(250112, 512)
  (encoder): MT5Stack(
    (embed_tokens): Embedding(250112, 512)
    (block): ModuleList(
      (0): MT5Block(
        (layer): ModuleList(
          (0): MT5LayerSelfAttention(
            (SelfAttention): MT5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): MT5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): MT5LayerFF(
            (DenseReluDense): MT5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
          

In [45]:
# Create a custom optimizer using torch.optim.AdamW
custom_optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3,
    eps=1e-8,
    weight_decay=0.01,
)

In [46]:
#pip install accelerate -U

In [47]:
# Define the TrainingArguments for fine-tuning
training_args = TrainingArguments(
    output_dir='D:\\Datasets\\Thesis Data Test',
    num_train_epochs=1,
    per_device_train_batch_size=5,
    gradient_accumulation_steps=8,
    evaluation_strategy="epoch",
    save_total_limit=0,
    save_steps=15000,
    learning_rate=1e-3,
    do_train=True,
    do_eval=True,
    remove_unused_columns=False,
    push_to_hub=False,
    report_to="none",
    load_best_model_at_end=False,
    lr_scheduler_type="cosine_with_restarts",
    warmup_steps=100,
    weight_decay=0.01,
    logging_dir='D:\\Datasets\\Thesis Data Test',
    logging_steps=200,
    
)


In [48]:
# Create a data collator for sequence-to-sequence tasks
data_collator = MyDataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=False,
    max_length=80,
    label_pad_token_id=tokenizer.pad_token_id,
)

In [49]:
# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset=validation_dataset,
    optimizers=(custom_optimizer, None),
)

In [ ]:
# Fine-tune the model
trainer.train()

In [62]:
'''import pandas as pd
import torch
from normalizer import normalize
from transformers import MT5ForConditionalGeneration, AutoTokenizer, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from torch.utils.data import Dataset, DataLoader

# Assuming you have the necessary imports and data loading steps

class Seq2SeqDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=128):
        self.input_text = data['input_text'].apply(normalize).tolist()
        self.labels = data['labels'].apply(normalize).tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.input_text)

    def __getitem__(self, idx):
        input_text = self.input_text[idx]
        label_text = self.labels[idx]

        # Tokenize the input text
        input_encodings = self.tokenizer(
            input_text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        # Tokenize the label text to get its 'input_ids' and 'attention_mask'
        label_encodings = self.tokenizer(
            label_text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )

        return {
            'input_ids': input_encodings['input_ids'].squeeze(),
            'attention_mask': input_encodings['attention_mask'].squeeze(),
            'labels': label_encodings['input_ids'].squeeze(),
        }

# Modify the data collation process to handle PyTorch tensors correctly
class MyDataCollatorForSeq2Seq(DataCollatorForSeq2Seq):
    def __call__(self, features):
        batch = {}
        batch["input_ids"] = torch.stack([feature["input_ids"] for feature in features])
        batch["attention_mask"] = torch.stack([feature["attention_mask"] for feature in features])

        # Labels should be processed differently for PyTorch tensors
        if isinstance(features[0]["labels"], torch.Tensor):
            batch["labels"] = torch.stack([feature["labels"] for feature in features])
        else:
            # Convert the list of lists to a PyTorch tensor
            batch["labels"] = torch.tensor([feature["labels"] for feature in features])

        return batch

# Load the saved model
model = MT5ForConditionalGeneration.from_pretrained("C:\\Users\\Mukaffi\\Desktop\\fariya\\sylhet_translation_mT5.pt\\sylhet_translation_mT5.pt")

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained("C:\\Users\Mukaffi\\Desktop\\fariya\\sylhet_tokenizer_mT5.json\\sylhet_tokenizer_mT5.json")

# Create train dataset
train_dataset = Seq2SeqDataset(train_data, tokenizer)

# Create train dataloader
train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True)

# Move the model to the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Create a custom optimizer using torch.optim.AdamW
custom_optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3,
    eps=1e-8,
    weight_decay=0.01,
)

# Define the TrainingArguments for fine-tuning
training_args = TrainingArguments(
    output_dir='D:\\Datasets\\Thesis Data Test',
    num_train_epochs=1,
    per_device_train_batch_size=6,
    gradient_accumulation_steps=8,
    evaluation_strategy="steps",
    eval_steps=10,
    save_total_limit=2,
    save_steps=15000,
    learning_rate=1e-3,
    do_train=True,
    do_eval=True,
    remove_unused_columns=False,
    push_to_hub=False,
    report_to="none",
    load_best_model_at_end=True,
    lr_scheduler_type="cosine_with_restarts",
    warmup_steps=100,
    weight_decay=0.01,
    logging_dir='D:\\Datasets\\Thesis Data Test',
    logging_steps=100,
)

# Create a data collator for sequence-to-sequence tasks
data_collator = MyDataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=False,
    max_length=128,
    label_pad_token_id=tokenizer.pad_token_id,
)

# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    optimizers=(custom_optimizer, None),
)

# Fine-tune the model
trainer.train()
'''

'import pandas as pd\nimport torch\nfrom normalizer import normalize\nfrom transformers import MT5ForConditionalGeneration, AutoTokenizer, DataCollatorForSeq2Seq, Trainer, TrainingArguments\nfrom torch.utils.data import Dataset, DataLoader\n\n# Assuming you have the necessary imports and data loading steps\n\nclass Seq2SeqDataset(Dataset):\n    def __init__(self, data, tokenizer, max_length=128):\n        self.input_text = data[\'input_text\'].apply(normalize).tolist()\n        self.labels = data[\'labels\'].apply(normalize).tolist()\n        self.tokenizer = tokenizer\n        self.max_length = max_length\n\n    def __len__(self):\n        return len(self.input_text)\n\n    def __getitem__(self, idx):\n        input_text = self.input_text[idx]\n        label_text = self.labels[idx]\n\n        # Tokenize the input text\n        input_encodings = self.tokenizer(\n            input_text,\n            truncation=True,\n            padding=\'max_length\',\n            max_length=self.max_l

# **Save the model**

In [63]:
from transformers import AutoModelForSeq2SeqLM

# Save the model
model.save_pretrained("E:\\Fariya\\translation_mT5.pt")

# Save the tokenizer
tokenizer.save_pretrained("E:\\Fariya\\tokenizer_mT5.json")



('E:\\Fariya\\tokenizer_mT5.json\\tokenizer_config.json',
 'E:\\Fariya\\tokenizer_mT5.json\\special_tokens_map.json',
 'E:\\Fariya\\tokenizer_mT5.json\\spiece.model',
 'E:\\Fariya\\tokenizer_mT5.json\\added_tokens.json',
 'E:\\Fariya\\tokenizer_mT5.json\\tokenizer.json')

# **Load the model again**

In [43]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# Load the saved model
model = AutoModelForSeq2SeqLM.from_pretrained("E:\\Fariya\\translation_mT5.pt")

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained("E:\\Fariya\\tokenizer_mT5.json")


In [27]:
!pip install datasets

In [28]:
!pip install python-Levenshtein

In [29]:
!pip install jiwer

In [30]:
# Move the model to the device (CPU or GPU)
model.to(device)

MT5ForConditionalGeneration(
  (shared): Embedding(250112, 512)
  (encoder): MT5Stack(
    (embed_tokens): Embedding(250112, 512)
    (block): ModuleList(
      (0): MT5Block(
        (layer): ModuleList(
          (0): MT5LayerSelfAttention(
            (SelfAttention): MT5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): MT5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): MT5LayerFF(
            (DenseReluDense): MT5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
          

In [31]:
!pip install rouge-score
#https://github.com/google-research/google-research/tree/master/rouge
#https://huggingface.co/spaces/evaluate-metric/rouge [Different types of ROUGE scores]

In [32]:
!pip install evaluate

In [33]:
import torch
import Levenshtein
from evaluate import load
# Define the move_to_device function
def move_to_device(batch, device):
    if isinstance(batch, torch.Tensor):
        return batch.to(device)
    elif isinstance(batch, list):
        return [move_to_device(item, device) for item in batch]
    elif isinstance(batch, dict):
        return {key: move_to_device(value, device) for key, value in batch.items()}
    else:
        return batch  # If it's not a tensor, list, or dict, leave it as is

# Load the evaluation metric for Character Error Rate (CER) and Word Error Rate (WER) and Exact Match(em)
cer_metric = load("cer")
wer_metric = load("wer")
meteor = load('meteor')
exact_match_metric = load("exact_match")

# Load BLEU and ROUGE metrics
bleu_metric = load("bleu")
rouge_metric = load('rouge')

# Initialize lists to store generated translations and references
generated_translations = []
references = []

# Generate translations for the test dataset
for batch in test_dataloader:
    # Move the batch to CUDA
    batch = move_to_device(batch, 'cuda')

    input_text = batch['input_ids']  # Access the input_text using the correct key
    labels = batch['labels']  # Access the labels using the correct key
    print(input_text)
    # Generate translations
    translation_ids = model.generate(input_text, max_length=50, num_beams=4, length_penalty=2.0, early_stopping=True)

    # Move the translation_ids to CPU to decode
    translation_ids = translation_ids.to('cpu')

    generated_translation = tokenizer.batch_decode(translation_ids, skip_special_tokens=True)

    generated_translations.extend(generated_translation)
    references.extend(tokenizer.batch_decode(labels, skip_special_tokens=True))  # Decoding the label IDs

# Make sure to move generated_translations back to CPU for evaluation if necessary
generated_translations = [translation if not isinstance(translation, str) else translation for translation in generated_translations]



[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Mukaffi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mukaffi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Mukaffi\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


tensor([[26130, 40256,  4089,  ...,     0,     0,     0],
        [  313,  7759, 12636,  ...,     0,     0,     0],
        [  486,   269,  2066,  ...,     0,     0,     0],
        ...,
        [  486,   272,   790,  ...,     0,     0,     0],
        [ 1494, 20815, 13636,  ...,     0,     0,     0],
        [ 4837,  3256,   416,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   501,  59954,  15233,  ...,      0,      0,      0],
        [   313,  41758,   3551,  ...,      0,      0,      0],
        [   259,    277,  13344,  ...,      0,      0,      0],
        ...,
        [  1829,    287,    259,  ...,      0,      0,      0],
        [   313, 161083,   9496,  ...,      0,      0,      0],
        [  5258,    569,    259,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  4879,    265,    304,  ...,      0,      0,      0],
        [   259,    264,    371,  ...,      0,      0,      0],
        [ 23419,    282, 218156,  ...,      0,      0,      0],
       

tensor([[   313,    545, 157914,  ...,      0,      0,      0],
        [   563,    287,  15388,  ...,      0,      0,      0],
        [   788, 111323,    287,  ...,      0,      0,      0],
        ...,
        [   313,  90492,    267,  ...,      0,      0,      0],
        [   313,  47757,    309,  ...,      0,      0,      0],
        [ 15737,   2108,   2109,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 2953,   304,   259,  ...,     0,     0,     0],
        [33494,   265,   358,  ...,     0,     0,     0],
        [  259,   277,  2009,  ...,     0,     0,     0],
        ...,
        [  313, 11750, 58503,  ...,     0,     0,     0],
        [  259,  6397,   790,  ..., 24257,   260,     1],
        [  259,   277, 88882,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   336,  19820,    287,  ...,      0,      0,      0],
        [  5594,   1503,    270,  ...,      0,      0,      0],
        [   313,  14721,    914,  ...,      0,      0,      0],
       

tensor([[  1669,    639, 116336,  ...,      0,      0,      0],
        [  8690,   3256,    416,  ...,      0,      0,      0],
        [  1071,    533,    261,  ...,      0,      0,      0],
        ...,
        [   486,  77366,    259,  ...,      0,      0,      0],
        [  5258,   6898,    260,  ...,      0,      0,      0],
        [  1124,    384,    259,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[53389, 12787,   259,  ...,     0,     0,     0],
        [  313, 45214,  6117,  ...,     0,     0,     0],
        [  313, 79467,   533,  ...,     0,     0,     0],
        ...,
        [ 1525,  2736,   702,  ...,     0,     0,     0],
        [ 5881, 30786,   261,  ...,     0,     0,     0],
        [ 1662,   418,   287,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   459,   7030,    259,  ...,      0,      0,      0],
        [  1385,    303, 165998,  ...,      0,      0,      0],
        [ 11502,    484,    261,  ...,      0,      0,      0],
       

tensor([[ 3946,   819,   277,  ...,     0,     0,     0],
        [  259, 18948,  2109,  ...,     0,     0,     0],
        [ 1669,   639,  3867,  ...,     0,     0,     0],
        ...,
        [11039,   265, 11047,  ...,     0,     0,     0],
        [  313,  7968,  3086,  ...,     0,     0,     0],
        [  486,   259,  6197,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  1819,    260,   4040,  ...,      0,      0,      0],
        [   259,    277,  35286,  ...,      0,      0,      0],
        [   313, 148277,    309,  ...,      0,      0,      0],
        ...,
        [   459,    283,    335,  ...,      0,      0,      0],
        [   486,    259, 168192,  ...,      0,      0,      0],
        [ 34583,    259,   9371,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 8834,  3042,   339,  ...,     0,     0,     0],
        [ 4837,  2119,  2109,  ...,     0,     0,     0],
        [ 4630,   259,  2220,  ...,     0,     0,     0],
        ...,
        [  5

tensor([[  1669,  31533,    281,  ...,      0,      0,      0],
        [  4837,    342,    776,  ...,      0,      0,      0],
        [   259,    277, 151478,  ...,      0,      0,      0],
        ...,
        [  1385,    639,    776,  ...,      0,      0,      0],
        [   259,    277,    357,  ...,      0,      0,      0],
        [  1494,   7834,    639,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   259,  10837,   2109,  ...,      0,      0,      0],
        [   563,  12558,    261,  ...,      0,      0,      0],
        [ 39579,    317, 216387,  ...,      0,      0,      0],
        ...,
        [  1641,    259,   3151,  ...,      0,      0,      0],
        [   313,   2349,    261,  ...,      0,      0,      0],
        [  1385,    639,    776,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   486,    259,  73443,  ...,      0,      0,      0],
        [  7468,  19968,   2440,  ...,      0,      0,      0],
        [   486, 130823,    

tensor([[   313,    566,    259,  ...,      0,      0,      0],
        [   259,  37284,    259,  ...,      0,      0,      0],
        [ 17876,    639, 108901,  ...,      0,      0,      0],
        ...,
        [   313,    277,    490,  ...,      0,      0,      0],
        [   336,    259,    270,  ...,      0,      0,      0],
        [  1385,    639,  92600,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  313, 38054,   261,  ...,     0,     0,     0],
        [ 7702,   609,   776,  ...,     0,     0,     0],
        [ 1071, 69841,   261,  ...,     0,     0,     0],
        ...,
        [  486, 39850, 16990,  ...,     0,     0,     0],
        [ 4630,   259,  2220,  ...,     0,     0,     0],
        [ 4837,   714,   259,  ...,     0,     0,     0]], device='cuda:0')
tensor([[10934,  7029,   345,  ...,     0,     0,     0],
        [ 1385,   339,  1371,  ...,     0,     0,     0],
        [  259,   264,  8656,  ...,     0,     0,     0],
        ...,
        [  3

tensor([[  5100,   3506,   3127,  ...,      0,      0,      0],
        [  4630,    639,  63703,  ...,      0,      0,      0],
        [   486,    272,    261,  ...,      0,      0,      0],
        ...,
        [   653,    296,    287,  ...,      0,      0,      0],
        [   313, 122444,    288,  ...,      0,      0,      0],
        [   259,    264,  20722,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   259,  14833,    261,  ...,      0,      0,      0],
        [  1029,    259,    266,  ...,      0,      0,      0],
        [   313,   4748,    287,  ...,      0,      0,      0],
        ...,
        [   313,  48222,    346,  ...,      0,      0,      0],
        [   313,  18402,   2426,  ...,      0,      0,      0],
        [   259, 105319,    639,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   486,    259, 145646,  ...,      0,      0,      0],
        [   313, 232150,    914,  ...,      0,      0,      0],
        [   486,    602,   5

tensor([[  1385,    339,   1469,  ...,      0,      0,      0],
        [   313,  64210,    336,  ...,      0,      0,      0],
        [   313, 119326,    261,  ...,      0,      0,      0],
        ...,
        [ 15737,   3993,   5105,  ...,      0,      0,      0],
        [  2610,  10295,    261,  ...,      0,      0,      0],
        [   313,  22851,  19425,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  9300,    259,  36678,  ...,      0,      0,      0],
        [   563,  12558,    261,  ...,      0,      0,      0],
        [  1102,    261,  16533,  ...,      0,      0,      0],
        ...,
        [   259,  10837,   5193,  ...,      0,      0,      0],
        [  1385,    639,   2130,  ...,      0,      0,      0],
        [   313, 119326,    261,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   313,  28269,   2952,  ...,      0,      0,      0],
        [  5546,    555,  28065,  ...,      0,      0,      0],
        [   486,    259, 114

tensor([[   313,  35286,    261,  ...,      0,      0,      0],
        [   563,    287,  15388,  ...,      0,      0,      0],
        [  1669,    259,  15176,  ...,      0,      0,      0],
        ...,
        [   486, 106092,   1614,  ...,      0,      0,      0],
        [   313,  10837,    277,  ...,      0,      0,      0],
        [   486,   2328,    639,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   313,  76982,    609,  ...,      0,      0,      0],
        [  2584,    714,  24337,  ...,      0,      0,      0],
        [ 15303,   7075,    335,  ...,      0,      0,      0],
        ...,
        [   313, 126629,    418,  ...,      0,      0,      0],
        [   313,  19374,    259,  ...,      0,      0,      0],
        [   259,  18948,   2109,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   313,  39715,    501,  ...,      0,      0,      0],
        [  2368,  72515,   3056,  ...,      0,      0,      0],
        [   313,  47757,    

tensor([[   259, 133930,    287,  ...,  18860,    289,      1],
        [  1118,  34606,   2155,  ...,      0,      0,      0],
        [  1385,    639,    259,  ...,      0,      0,      0],
        ...,
        [  1829,    790,   3785,  ...,      0,      0,      0],
        [  5126,    259,   2220,  ...,      0,      0,      0],
        [  1669, 132331,    345,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  259,   277, 21490,  ...,     0,     0,     0],
        [  441, 16289,   415,  ...,     0,     0,     0],
        [  336,  7176,   390,  ...,     0,     0,     0],
        ...,
        [ 9300,   261,   289,  ...,     0,     0,     0],
        [  313, 15604,   265,  ...,     0,     0,     0],
        [  486,   272,   287,  ...,     0,     0,     0]], device='cuda:0')
tensor([[11076,   259, 42822,  ...,     0,     0,     0],
        [ 2953,   259, 46531,  ...,     0,     0,     0],
        [ 6928,   261,   304,  ...,     0,     0,     0],
        ...,
        [ 28

tensor([[ 4837,  2561,   261,  ...,     0,     0,     0],
        [  313,  9248,   898,  ...,     0,     0,     0],
        [  313, 16730, 30363,  ...,     0,     0,     0],
        ...,
        [  259,   277,  6397,  ...,     0,     0,     0],
        [  336,   783,  5038,  ...,     0,     0,     0],
        [ 1477,   287, 14802,  ...,     0,     0,     0]], device='cuda:0')
tensor([[ 1669, 70418,   345,  ...,     0,     0,     0],
        [13889,  7834,   639,  ...,     0,     0,     0],
        [23632,  2756, 10893,  ...,     0,     0,     0],
        ...,
        [  259, 33644,   533,  ...,     0,     0,     0],
        [  259, 11517,   812,  ...,     0,     0,     0],
        [  259,   277, 38054,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  563,   714,   259,  ...,     0,     0,     0],
        [  313, 90492,  2454,  ...,     0,     0,     0],
        [  313, 28269, 66196,  ...,     0,     0,     0],
        ...,
        [ 2584,   259,  3543,  ...,     0,     0,     0

tensor([[  259, 52386,   277,  ...,     0,     0,     0],
        [ 1306,   259, 50915,  ...,     0,     0,     0],
        [ 4837,   287,  1097,  ...,     0,     0,     0],
        ...,
        [15737,  4976,   261,  ...,     0,     0,     0],
        [ 1306, 10893,   345,  ...,     0,     0,     0],
        [ 4837,   259,  1616,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   313,  64286,    259,  ...,      0,      0,      0],
        [   313,  15206,    609,  ...,      0,      0,      0],
        [  5258,    790,    305,  ...,      0,      0,      0],
        ...,
        [ 14197,    309,    259,  ...,      0,      0,      0],
        [   313, 159050,    305,  ...,      0,      0,      0],
        [  5126,   1070,   1537,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  1385,    639,   2561,  ...,      0,      0,      0],
        [  1494,    639,    287,  ...,      0,      0,      0],
        [   431,  13544,    286,  ...,      0,      0,      0],
       

tensor([[   313, 129017,    259,  ...,      0,      0,      0],
        [  1662,   2109,   1638,  ...,      0,      0,      0],
        [   259,    277, 170667,  ...,      0,      0,      0],
        ...,
        [   259,   6397,   2621,  ...,      0,      0,      0],
        [  1494,  26471,    345,  ...,      0,      0,      0],
        [  1669,  40574,    345,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  486,   259, 70577,  ...,     0,     0,     0],
        [ 2845,   259, 97510,  ...,     0,     0,     0],
        [  313, 10916,   351,  ...,     0,     0,     0],
        ...,
        [  313, 37477,   287,  ...,     0,     0,     0],
        [  313,  2349,   261,  ...,     0,     0,     0],
        [ 8672,  4065,  6557,  ...,     0,     0,     0]], device='cuda:0')
tensor([[ 2585,   259, 93298,  ...,     0,     0,     0],
        [ 5258,   569,   639,  ...,     0,     0,     0],
        [  259,   277, 95841,  ...,     0,     0,     0],
        ...,
        [  4

tensor([[ 6928,   533,   790,  ...,     0,     0,     0],
        [28893,   265,   264,  ...,     0,     0,     0],
        [  336,   259,   277,  ...,     0,     0,     0],
        ...,
        [ 4837,   514,   287,  ...,     0,     0,     0],
        [  313,   566,  7671,  ...,     0,     0,     0],
        [  458,   277, 24153,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   336,   1101,  19737,  ...,      0,      0,      0],
        [   313, 185953,  23191,  ...,      0,      0,      0],
        [  1916,    287,    259,  ...,      0,      0,      0],
        ...,
        [   486,  11285,  51366,  ...,      0,      0,      0],
        [   486,    259, 128610,  ...,      0,      0,      0],
        [  4837,    331,    277,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  336,   259, 28387,  ...,     0,     0,     0],
        [ 1071, 69841,   261,  ...,     0,     0,     0],
        [77043, 79554,   455,  ...,     0,     0,     0],
        ...,
        [595

tensor([[   313,  35619,    309,  ...,      0,      0,      0],
        [   664,    277,  57302,  ...,      0,      0,      0],
        [   486,  29580,   2109,  ...,      0,      0,      0],
        ...,
        [  1385,    639,   4927,  ...,      0,      0,      0],
        [   313,    424, 142928,  ...,      0,      0,      0],
        [   486,   5382,    304,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  4837,    261,    776,  ...,      0,      0,      0],
        [  1102,   2155,    609,  ...,      0,      0,      0],
        [  8035, 187538,    527,  ...,      0,      0,      0],
        ...,
        [  1477,    288,  56926,  ...,      0,      0,      0],
        [  1669,    639,  35656,  ...,      0,      0,      0],
        [   313,    566,    728,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  313, 60845,   702,  ...,     0,     0,     0],
        [  259,   277,   566,  ...,     0,     0,     0],
        [  313,  2009,   272,  ...,     

tensor([[   259, 101388,    265,  ...,      0,      0,      0],
        [   298,    259, 112673,  ...,      0,      0,      0],
        [   486,   2956,   3005,  ...,      0,      0,      0],
        ...,
        [   313, 119326,    914,  ...,      0,      0,      0],
        [   313,  14721,    259,  ...,      0,      0,      0],
        [   259,  14833,    261,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 10266,    261,   5546,  ...,      0,      0,      0],
        [  1829,    287,    259,  ...,      0,      0,      0],
        [   259,    277, 225878,  ...,      0,      0,      0],
        ...,
        [   259, 199378,    270,  ...,      0,      0,      0],
        [  7961,    330,  35714,  ...,      0,      0,      0],
        [   313, 143267,    609,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   259,    277,  35286,  ...,      0,      0,      0],
        [  2953,   3117,    261,  ...,      0,      0,      0],
        [   313, 119326,    

tensor([[ 1385,   339,   776,  ...,     0,     0,     0],
        [  313, 95841,   277,  ...,     0,     0,     0],
        [73670,  3031,   776,  ...,     0,     0,     0],
        ...,
        [  336, 11763,   521,  ...,     0,     0,     0],
        [ 5100, 20150,   305,  ...,     0,     0,     0],
        [  336,  3031,   776,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   259, 129532,    702,  ...,      0,      0,      0],
        [  1662,   4047,   2119,  ...,      0,      0,      0],
        [   653,    261,    375,  ...,      0,      0,      0],
        ...,
        [   259,   6397,   2455,  ...,      0,      0,      0],
        [   259,  14833,    261,  ...,      0,      0,      0],
        [   563,    259,  82977,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   336,    639, 108901,  ...,      0,      0,      0],
        [  2368,   3825,    309,  ...,      0,      0,      0],
        [   313,  65237,    277,  ...,      0,      0,      0],
       

tensor([[   313,   2349,    261,  ...,      0,      0,      0],
        [  5258,    639,    259,  ...,      0,      0,      0],
        [   313,  19374,    521,  ...,      0,      0,      0],
        ...,
        [  5987, 196368,   4089,  ...,      0,      0,      0],
        [   313,  64210,    609,  ...,      0,      0,      0],
        [   313,    566,    783,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 5126,   639,   287,  ...,     0,     0,     0],
        [ 1662,   259, 88491,  ...,     0,     0,     0],
        [ 1662,  5150, 58289,  ...,     0,     0,     0],
        ...,
        [  431,   277, 17512,  ...,     0,     0,     0],
        [  313, 64210,   288,  ...,     0,     0,     0],
        [  313, 96465,   261,  ...,     0,     0,     0]], device='cuda:0')
tensor([[18241,   347, 25626,  ...,     0,     0,     0],
        [ 1669,   259, 16694,  ...,     0,     0,     0],
        [  336,  1425, 15907,  ...,     0,     0,     0],
        ...,
        [ 46

tensor([[  1525,    790,    259,  ...,      0,      0,      0],
        [   336,    639,   2469,  ...,      0,      0,      0],
        [ 35331, 206542,   2052,  ...,      0,      0,      0],
        ...,
        [ 35331, 206542,    475,  ...,      0,      0,      0],
        [ 11968,    283,    259,  ...,      0,      0,      0],
        [ 75380, 199108,    921,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[15737, 58641,   263,  ...,     0,     0,     0],
        [ 4630, 15740,   304,  ...,     0,     0,     0],
        [ 1669,   639,   776,  ...,     0,     0,     0],
        ...,
        [ 1525,   344,   259,  ...,     0,     0,     0],
        [ 1243,  1384,   503,  ...,     0,     0,     0],
        [ 1669,  1425, 16931,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  313, 38589,   521,  ...,     0,     0,     0],
        [  486,  4622, 78742,  ...,     0,     0,     0],
        [42919,   259, 14196,  ...,     0,     0,     0],
        ...,
        [ 51

tensor([[   313, 151478, 199108,  ...,      0,      0,      0],
        [   259,   6397,    790,  ...,      0,      0,      0],
        [   313,  61379,    914,  ...,      0,      0,      0],
        ...,
        [  4630,   3869,    263,  ...,      0,      0,      0],
        [  1306,  17393,    345,  ...,      0,      0,      0],
        [  4837,   2108,    418,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  259, 50509,   484,  ...,     0,     0,     0],
        [ 1243,   448,   520,  ...,     0,     0,     0],
        [17876,   344,   287,  ...,     0,     0,     0],
        ...,
        [ 4630, 12122,   345,  ...,     0,     0,     0],
        [ 1560, 89477, 42264,  ...,     0,     0,     0],
        [  259,   264,  2455,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  486, 11208,   639,  ...,     0,     0,     0],
        [ 1669,   259,   263,  ...,     0,     0,     0],
        [ 2485,  2108,   259,  ...,     0,     0,     0],
        ...,
        [ 25

tensor([[  8009,   1522,   2404,  ...,      0,      0,      0],
        [   336,    259,  22405,  ...,      0,      0,      0],
        [   313,   2009,    259,  ...,      0,      0,      0],
        ...,
        [   313, 123038,    484,  ...,      0,      0,      0],
        [  4837,    261,    344,  ...,      0,      0,      0],
        [   486,    272,    287,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   486,  22048,   1052,  ...,      0,      0,      0],
        [   431,    277,  17512,  ...,      0,      0,      0],
        [   259,  12115,  34455,  ...,      0,      0,      0],
        ...,
        [  2953,   5150,    390,  ...,      0,      0,      0],
        [   313, 119326,    261,  ...,      0,      0,      0],
        [  5258,    569,    305,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   259,  22841, 235500,  ...,      0,      0,      0],
        [   313,   2594,    368,  ...,      0,      0,      0],
        [   313,  64210,    

tensor([[ 1385,   277,   263,  ...,     0,     0,     0],
        [  313,  9248,   783,  ...,     0,     0,     0],
        [ 1669, 22705,   345,  ...,     0,     0,     0],
        ...,
        [  313,  2009,   259,  ...,     0,     0,     0],
        [  486,  6604, 86911,  ...,     0,     0,     0],
        [  313,   478, 10517,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  313,  4129,  4645,  ...,     0,     0,     0],
        [  298, 28746,   344,  ...,     0,     0,     0],
        [  313,  8729,  4936,  ...,     0,     0,     0],
        ...,
        [ 1494, 11940,   880,  ...,     0,     0,     0],
        [ 1669,   259,  3659,  ...,     0,     0,     0],
        [  486, 56388, 20815,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  259, 10837, 27696,  ...,     0,     0,     0],
        [  313,  6397,  3031,  ...,     0,     0,     0],
        [  486,  7084, 16603,  ...,     0,     0,     0],
        ...,
        [ 3342,  1089,   273,  ...,     0,     0,     0

tensor([[  313,   566, 64578,  ...,     0,     0,     0],
        [  313, 38054,   261,  ...,     0,     0,     0],
        [  259,   264,  1170,  ...,     0,     0,     0],
        ...,
        [82161,  1582, 96569,  ...,     0,     0,     0],
        [ 2584, 49889,   259,  ...,     0,     0,     0],
        [ 1829,  4875,   336,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   313,    566,    259,  ...,      0,      0,      0],
        [   486,    259, 112145,  ...,      0,      0,      0],
        [   486,   2956,    259,  ...,      0,      0,      0],
        ...,
        [   746,  14467,   9502,  ...,      0,      0,      0],
        [ 13805,    880,    484,  ...,      0,      0,      0],
        [   313,    566,    898,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 8875,   261,   336,  ...,   910, 11551,     1],
        [  313, 13905, 14701,  ...,     0,     0,     0],
        [11076,   259,   262,  ...,     0,     0,     0],
        ...,
        [138

tensor([[   926,    714,    336,  ...,      0,      0,      0],
        [   486,    259,    265,  ...,      0,      0,      0],
        [  2313, 131009,    299,  ...,      0,      0,      0],
        ...,
        [  1641,    520,  17523,  ...,      0,      0,      0],
        [   259,  29655,   3031,  ...,      0,      0,      0],
        [   313,   4129,   4645,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  313,   357,   263,  ...,     0,     0,     0],
        [73670,  3031,   776,  ...,     0,     0,     0],
        [  336, 19820,   455,  ...,     0,     0,     0],
        ...,
        [ 1385,   339,  6274,  ...,   259, 25530,     1],
        [  313, 15206,   609,  ...,     0,     0,     0],
        [  313, 10837,   418,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   486,  53852,    639,  ...,      0,      0,      0],
        [  1494,  17231,    639,  ...,      0,      0,      0],
        [ 11055,    263,    304,  ...,      0,      0,      0],
       

tensor([[   336,    259,  22405,  ...,      0,      0,      0],
        [   486,  18582,   6812,  ...,      0,      0,      0],
        [   486,   2328,    639,  ...,      0,      0,      0],
        ...,
        [ 39579,   3117,    336,  ...,      0,      0,      0],
        [ 70600,  11132,  15162,  ...,      0,      0,      0],
        [   313, 232150,   5987,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   259,    277,  18402,  ...,      0,      0,      0],
        [  8377,  12112,  43847,  ...,      0,      0,      0],
        [   486,    259,  98423,  ...,      0,      0,      0],
        ...,
        [  1829,    790, 211112,  ...,      0,      0,      0],
        [   259,  29655,    342,  ...,      0,      0,      0],
        [   313,  13344,   5387,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  259, 12115,   418,  ...,     0,     0,     0],
        [ 4630,   639,   259,  ...,     0,     0,     0],
        [  313,   566, 22491,  ...,     

tensor([[ 13889,  74126,    541,  ...,      0,      0,      0],
        [ 10934,  96318,    424,  ...,      0,      0,      0],
        [   259,  22841,    287,  ...,      0,      0,      0],
        ...,
        [   486,   1097,    790,  ...,      0,      0,      0],
        [   313, 189048,    305,  ...,      0,      0,      0],
        [   259,  12115,   2956,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  259, 18948,   261,  ...,     0,     0,     0],
        [  336,   898,   342,  ...,     0,     0,     0],
        [ 1829,   521,   264,  ...,     0,     0,     0],
        ...,
        [  486,   259, 39852,  ...,     0,     0,     0],
        [ 4630,   639,   288,  ...,     0,     0,     0],
        [  486, 10275,   304,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   298,   7084,    259,  ...,      0,      0,      0],
        [  1916,    287,    259,  ...,      0,      0,      0],
        [  1306,  35042,    345,  ...,      0,      0,      0],
       

tensor([[ 2455,  1783, 37035,  ...,     0,     0,     0],
        [ 1385,   259,  3659,  ...,     0,     0,     0],
        [ 6928,  1638, 14426,  ...,     0,     0,     0],
        ...,
        [  486,   776,  2451,  ...,     0,     0,     0],
        [  298,   400, 55976,  ...,     0,     0,     0],
        [ 1385,   339,   259,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   313,   9248,    898,  ...,      0,      0,      0],
        [  2368,  42187,    414,  ...,      0,      0,      0],
        [ 31716,    265,  16826,  ...,      0,      0,      0],
        ...,
        [  1385,    339,    332,  ...,      0,      0,      0],
        [   313,    511,    286,  ...,      0,      0,      0],
        [   336,    259, 192405,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  1494,    259,    286,  ...,      0,      0,      0],
        [ 11100, 105348,   2348,  ...,    262,  20150,      1],
        [  1494,    639,    751,  ...,      0,      0,      0],
       

tensor([[   259,  35129,   9713,  ...,      0,      0,      0],
        [   259,  76569,   2621,  ...,      0,      0,      0],
        [150038,    309,    609,  ...,      0,      0,      0],
        ...,
        [   313,   2594,    368,  ...,      0,      0,      0],
        [ 61690,    701,  40518,  ...,      0,      0,      0],
        [  1029,   7834,    259,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   486,  62125,  93711,  ...,      0,      0,      0],
        [   259, 162942,   3354,  ...,      0,      0,      0],
        [  7961,    301, 102119,  ...,      0,      0,      0],
        ...,
        [ 38718,    277,    263,  ...,      0,      0,      0],
        [   486,  54714,    639,  ...,      0,      0,      0],
        [  1641,    287,    568,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  336,   259, 26702,  ...,     0,     0,     0],
        [  259,   277,  2349,  ...,     0,     0,     0],
        [  486,  7084,   259,  ...,     

tensor([[  5258,    639,    375,  ...,      0,      0,      0],
        [ 15737,    261,    259,  ...,      0,      0,      0],
        [   298,   6675,   2653,  ...,      0,      0,      0],
        ...,
        [120663,    299,    418,  ...,      0,      0,      0],
        [  2584,    287,   3162,  ...,      0,      0,      0],
        [ 47125,   1274,    305,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 1071, 69841,   261,  ...,     0,     0,     0],
        [ 5100,   342,   521,  ...,     0,     0,     0],
        [ 2368,   335, 16527,  ...,     0,     0,     0],
        ...,
        [49104,   454,  1865,  ...,     0,     0,     0],
        [ 1662,   259, 24083,  ...,     0,     0,     0],
        [  313, 22968, 67179,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  486,  3029,   304,  ...,     0,     0,     0],
        [ 1385,   259, 88583,  ...,     0,     0,     0],
        [  336, 26766,   375,  ...,     0,     0,     0],
        ...,
        [  3

tensor([[   259,    264,   1170,  ...,      0,      0,      0],
        [  1385,    639,    259,  ...,      0,      0,      0],
        [  2368,   1719,    281,  ...,    281,    259,      1],
        ...,
        [   515, 206379,    261,  ...,      0,      0,      0],
        [ 44746,    298,    447,  ...,      0,      0,      0],
        [  1525,    336,   3609,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[1669,  390, 2739,  ...,    0,    0,    0],
        [1306, 1425,  259,  ...,    0,    0,    0],
        [6898,  260,  489,  ...,    0,    0,    0],
        ...,
        [ 313,  566,  259,  ..., 5810, 1001,    1],
        [ 313,  478,  334,  ...,    0,    0,    0],
        [4837,  533,  339,  ...,    0,    0,    0]], device='cuda:0')
tensor([[  5881, 152379,    276,  ...,      0,      0,      0],
        [ 36424,  31970,   2440,  ...,      0,      0,      0],
        [   259,  10837,   2718,  ...,      0,      0,      0],
        ...,
        [   313,  65237,    41

tensor([[  1102,    259,    262,  ...,      0,      0,      0],
        [   486,  42187,    305,  ...,      0,      0,      0],
        [   313,  90492,   2454,  ...,      0,      0,      0],
        ...,
        [   486,   3005,    295,  ...,      0,      0,      0],
        [  1829,    790,   4875,  ...,      0,      0,      0],
        [   313, 119326,    261,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   313,    566,   1607,  ...,      0,      0,      0],
        [  7961,    287,    276,  ...,      0,      0,      0],
        [  1669,   1425,    259,  ...,      0,      0,      0],
        ...,
        [   352,    260,  96390,  ...,      0,      0,      0],
        [   259,  64528, 117850,  ...,      0,      0,      0],
        [ 14197,    309,      1,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 5912,  2725,   261,  ...,     0,     0,     0],
        [ 1385,   510, 12862,  ...,     0,     0,     0],
        [  313,   357,   276,  ...,     

tensor([[  371,   277, 67423,  ...,     0,     0,     0],
        [ 4630,  5897,  1001,  ...,     0,     0,     0],
        [  259, 10837,  2109,  ...,     0,     0,     0],
        ...,
        [  259,   277, 12602,  ...,     0,     0,     0],
        [ 1170,  2192, 72121,  ...,     0,     0,     0],
        [ 1385,  8103, 29479,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  4630,    639,    259,  ...,      0,      0,      0],
        [   313,   2349,    914,  ...,      0,      0,      0],
        [   313, 170299,    270,  ...,      0,      0,      0],
        ...,
        [  5258,    569,    259,  ...,      0,      0,      0],
        [  4630,  17577,    345,  ...,      0,      0,      0],
        [222945,   5691,  12077,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  1641,    287,    475,  ...,      0,      0,      0],
        [   313,   9560,   3256,  ...,      0,      0,      0],
        [   313,  64528, 117850,  ...,      0,      0,      0],
       

tensor([[  3897, 101924,    265,  ...,      0,      0,      0],
        [   313,   5546,  27617,  ...,      0,      0,      0],
        [  1306,   1425,    259,  ...,      0,      0,      0],
        ...,
        [   313,  45214,   1070,  ...,      0,      0,      0],
        [ 82161,   1582,  63124,  ...,      0,      0,      0],
        [   313,  22968,   9713,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   313,  90492,    914,  ...,      0,      0,      0],
        [  1669,  93494,    299,  ...,      0,      0,      0],
        [   926,  19078,    287,  ...,      0,      0,      0],
        ...,
        [  2610,   6504,    639,  ...,      0,      0,      0],
        [   352, 108892,   7594,  ...,      0,      0,      0],
        [ 11076,    259,    262,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  1669,    259,  16694,  ...,      0,      0,      0],
        [   486,    272,    336,  ...,      0,      0,      0],
        [   320, 220175,    

tensor([[  313, 64210,   416,  ...,     0,     0,     0],
        [ 1669, 15740, 22890,  ...,     0,     0,     0],
        [  501, 59004, 16826,  ...,     0,     0,     0],
        ...,
        [59877, 12004,   345,  ...,     0,     0,     0],
        [  259,   277,  2349,  ...,     0,     0,     0],
        [ 1669,   344,   259,  ...,     0,     0,     0]], device='cuda:0')
tensor([[ 47012,    276,    416,  ...,      0,      0,      0],
        [  8672,    259,    438,  ...,      0,      0,      0],
        [  4993,    450, 108815,  ...,      0,      0,      0],
        ...,
        [   313, 210381,    304,  ...,      0,      0,      0],
        [  1669,    259,   3659,  ...,      0,      0,      0],
        [  5246,    444,    533,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  1102,   9137,    484,  ...,      0,      0,      0],
        [  1669,  18996,    345,  ...,      0,      0,      0],
        [   486, 187866,   2104,  ...,      0,      0,      0],
       

tensor([[  1525,    521,    259,  ...,      0,      0,      0],
        [  5100,    342,    521,  ...,      0,      0,      0],
        [   313, 116048,    281,  ...,      0,      0,      0],
        ...,
        [  1669,    259,  57830,  ...,      0,      0,      0],
        [  1669,  39547,    345,  ...,      0,      0,      0],
        [ 31716,    265,  77498,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[   336,    738,   5683,  ...,      0,      0,      0],
        [   313,  38054,    309,  ...,      0,      0,      0],
        [   313, 134646,   6225,  ...,      0,      0,      0],
        ...,
        [   313,  90492,    261,  ...,      0,      0,      0],
        [   313,  11750,    914,  ...,      0,      0,      0],
        [ 13805,    880,    484,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  313, 35286,   584,  ...,     0,     0,     0],
        [  336, 37287,   345,  ...,     0,     0,     0],
        [ 6898,   260, 59679,  ...,     

tensor([[   336,    277,   1578,  ...,      0,      0,      0],
        [   313,  19374,   2119,  ...,      0,      0,      0],
        [   259, 129145, 234757,  ...,      0,      0,      0],
        ...,
        [   313,    590,  20958,  ...,      0,      0,      0],
        [   313,  35286,    639,  ...,      0,      0,      0],
        [   259,  39609,    288,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[  336,   783,   332,  ...,     0,     0,     0],
        [48671,  1425,   790,  ...,     0,     0,     0],
        [ 6282,   347, 43540,  ...,     0,     0,     0],
        ...,
        [15255, 22036,   309,  ...,     0,     0,     0],
        [ 8480,  9430, 54384,  ...,     0,     0,     0],
        [  313, 38054,   261,  ...,     0,     0,     0]], device='cuda:0')
tensor([[   336,  19820,    533,  ...,      0,      0,      0],
        [  1794,   2155,    414,  ...,      0,      0,      0],
        [   313,   8035,    326,  ...,      0,      0,      0],
       

tensor([[  259,   264,   764,  ...,     0,     0,     0],
        [ 8035,   259,   272,  ...,     0,     0,     0],
        [ 6928,   261,  4089,  ...,     0,     0,     0],
        ...,
        [  313,   403,  2322,  ...,     0,     0,     0],
        [  259, 33806,   259,  ...,     0,     0,     0],
        [  259,   277, 22851,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  336,   259, 16694,  ...,     0,     0,     0],
        [  313, 95841,   277,  ...,     0,     0,     0],
        [  313,   566,  2469,  ...,     0,     0,     0],
        ...,
        [  486,  4119,  3212,  ...,     0,     0,     0],
        [ 4630, 18996,   345,  ...,     0,     0,     0],
        [ 3398, 10406,   309,  ...,     0,     0,     0]], device='cuda:0')
tensor([[  5258, 106018,   8547,  ...,    305,   1866,      1],
        [  8505,    339,   1638,  ...,      0,      0,      0],
        [   259,  18948,   3609,  ...,      0,      0,      0],
        ...,
        [   313, 159050,   1098,  ...

tensor([[  313, 18402,   783,  ...,     0,     0,     0],
        [  313,   357, 59353,  ...,     0,     0,     0],
        [  313,   566, 11763,  ...,     0,     0,     0],
        ...,
        [  313,   806, 20112,  ...,     0,     0,     0],
        [  313,  2349, 38355,  ...,     0,     0,     0],
        [19194,  9199,  3785,  ...,     0,     0,     0]], device='cuda:0')
tensor([[ 14197,    261,    259,  ...,      0,      0,      0],
        [   259,  38589,  38718,  ...,      0,      0,      0],
        [   486,    382, 194023,  ...,      0,      0,      0],
        ...,
        [  6550,   7655,  25483,  ...,      0,      0,      0],
        [   313,  35619,    261,  ...,      0,      0,      0],
        [  1306,   5150,    390,  ...,      0,      0,      0]],
       device='cuda:0')
tensor([[ 2841,   790, 44776,  ...,     0,     0,     0],
        [15303, 59154,  6979,  ...,     0,     0,     0],
        [ 1669, 19820,   259,  ...,     0,     0,     0],
        ...,
        [742

In [34]:
print("Number of generated translations:", len(generated_translations))
print("Number of references:", len(references))

Number of generated translations: 25417
Number of references: 25417


In [35]:
print(generated_translations)

["Altamira la regarda d'un etonnement ; Julien n'osait pas la regarder.", "-- Deja vide, cor-boeuf! et je n'ai plus d'argent!", "Le sourd l'avait referme derriere lui quand il entrait dans la galerie; Jehan s'etait cache derriere un roi de pierre, ne voulant pas respirer, et fixant sur", 'Vous ne ferez pas plus que de dire adieu, Jane?', "Vous ne trompez pas une femme comme moi, mon cher ami, malheureusement, je suis encore trop jeune et trop bonne pour accepter la partie que vous m'offrez.", "-- Bon! s'ecria-t-elle, j'aime que vous me pensez ainsi.", "Quelquefois je sortis dans elle pour me distraire, mais aucun voyage plus dangereux ne m'en allait jamais, a peine au-dessus d'une pierre ou deux de la ", "Enfin il se sentait affaibli par l'idee du devoir.", "On eut cru que je n'aurais pas eu le moindre reflet sur mon esprit de ma situation, pendant que je fis cette barque, mais j'aurais cru immediatement songer a", '-- Les imbeciles! repeta M. Hennebeau; suis-je heureux?', "J'obeis ses

In [36]:
#print(references[10])

In [37]:
# Calculate Character Error Rate (CER) and Word Error Rate (WER)
results_CER = cer_metric.compute(predictions=generated_translations, references=references)
results_WER = wer_metric.compute(predictions=generated_translations, references=references)

# Calculate Exact Match (EM) and METEOR(M)
results_em = exact_match_metric.compute(predictions=generated_translations, references=references)
results_met = meteor.compute(predictions=generated_translations, references=references)

# Calculate Bilingual Evaluation Understudy (BLEU) and Recall-Oriented Understudy for Gisting Evaluation (ROUGE)
results_bleu = bleu_metric.compute(predictions=generated_translations, references=references)
results_rouge = rouge_metric.compute(predictions=generated_translations, references=references)


# Calculate Levenshtein Distance
levenshtein_distances = [Levenshtein.distance(generated, reference) for generated, reference in zip(generated_translations, references)]


In [41]:
print(results_CER)
print(results_WER)
print(results_em)
print(results_met)
print(results_bleu)
print(results_rouge)


0.525822304529566
0.7046261002886353
{'exact_match': 0.02069481055986151}
{'meteor': 0.4805252735868863}
{'bleu': 0.2082920785574104, 'precisions': [0.5777795946733165, 0.32172533191898545, 0.19995666651461935, 0.12818583085694374], 'brevity_penalty': 0.7928059699645588, 'length_ratio': 0.8115718684060356, 'translation_length': 489235, 'reference_length': 602824}
{'rouge1': 0.5313357441338813, 'rouge2': 0.30747080760673773, 'rougeL': 0.5001136603163561, 'rougeLsum': 0.5001265135912111}


In [44]:
total_correct = 0
total_samples = len(references)

for generated, reference in zip(generated_translations, references):
    levenshtein_distance = Levenshtein.distance(generated, reference)
    max_length = max(len(generated), len(reference))
    accuracy = 1 - (levenshtein_distance / max_length)
    if accuracy >= 0.5:  # Adjust the threshold as needed
        total_correct += 1

accuracy = total_correct / total_samples
print("Accuracy:", accuracy)


Accuracy: 0.5792973206908761


# **Save translation results to a csv file**

In [40]:
import pandas as pd

# Create a DataFrame to store translations
translation_df = pd.DataFrame({
    'input_text': test_data['input_text'],  # Assuming 'test_data' contains your test dataset
    'labels': references,
    'translations': generated_translations
})

# Save translations to a CSV file
#translation_df.to_csv("/content/drive/MyDrive/sylhet_translation_results/sylhet_translation_mT5/model_fine_tuned/mBERT_sylhet_translation.csv", index=False)
# Save translations to a CSV file
translation_df.to_excel('E:\\Fariya\\translation\\fr_translations_mT5.xlsx', index=False)


OSError: Cannot save file into a non-existent directory: 'E:\Fariya\translation'